#on:
#  push: {}

jobs:
  build-base-amd64:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: ${{ steps.meta.outputs.tags }}-amd64
          labels: ${{ steps.meta.outputs.labels }}

# it's too slow build
#  build-base-arm64:
#    runs-on: ubuntu-22.04
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - name: Git checkout
#        uses: actions/checkout@v2
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to the Container registry
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v4.1.1
#        with:
#          images: |
#            ghcr.io/${{ github.repository }}
#
#      - name: Build and push Docker images
#        uses: docker/build-push-action@v3.2.0
#        with:
#          context: .
#          file: Dockerfile.base
#          push: true
#          platforms: linux/arm64
#          tags: ${{ steps.meta.outputs.tags }}-arm
#          labels: ${{ steps.meta.outputs.labels }}