on:
  push: {} # TODO: change to be on tag

jobs:
  generate_ruby_gem:
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v2
        with:
          path: cheminee

      - uses: actions/checkout@v3
        with:
          repository: assaydepot/cheminee-ruby.git
          path: cheminee-ruby
          ref: main

      - name: Install rdkit
        run: |
          sudo bash -c "echo 'deb [trusted=yes] https://rdkit-rs-debian.s3.amazonaws.com jammy main' > /etc/apt/sources.list.d/rdkit-rs.list"
          sudo apt-get update
          sudo apt-get install -y build-essential librdkit-dev libssl-dev libboost1.74-dev libboost-serialization1.74-dev pkg-config

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Cheminee
        run: cargo install --path cheminee/

      - name: Write Out Spec
        run: cheminee rest-api-server spec -o cheminee-ruby/openapi.json

      - name: Generate Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: ruby
          config-file: cheminee-ruby/openapi-generator-config.json
          openapi-file: cheminee-ruby/openapi.json
          command-args: "--additional-properties='gemVersion=2.0.1' --output=cheminee-ruby"

      - run: ls -alh .; ls -alh cheminee-ruby; cd cheminee-ruby; git status