on:
  push:
    tags: [ "*" ]

jobs:
  generate_ruby_gem:
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v2
        with:
          path: cheminee

      - uses: actions/checkout@v3
        with:
          repository: assaydepot/cheminee-ruby.git
          path: cheminee-ruby
          ref: main
          token: ${{ secrets.SCIENTIST_SERVICE_CHEMINEE_RUBY_GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libboost-iostreams-dev libboost-serialization-dev pkg-config curl tar unzip

      - name: Install RDKit
        run: |
          cd /tmp
          if [ $(dpkg --print-architecture) = "amd64" ]; then
            curl -O https://rdkit-rs-debian.s3.eu-central-1.amazonaws.com/rdkit_2024_09_1_ubuntu_22_04_amd64.tar.gz
            sudo tar xf rdkit_2024_09_1_ubuntu_22_04_amd64.tar.gz
          else
            curl -O https://rdkit-rs-debian.s3.eu-central-1.amazonaws.com/rdkit_2024_09_1_ubuntu_22_04_arm64.tar.gz
            sudo tar xf rdkit_2024_09_1_ubuntu_22_04_arm64.tar.gz
          fi
          sudo mv /tmp/rdkit-Release_2024_09_1/Code /usr/local/include/rdkit
          sudo mv /tmp/rdkit-Release_2024_09_1/build/lib/* /usr/lib/
          sudo rm -rf /tmp/*

      - name: Install Tensorflow
        run: |
          cd /tmp
          if [ $(dpkg --print-architecture) = "amd64" ]; then
            curl -O https://files.pythonhosted.org/packages/5b/00/af89cb211fc96ffdebb52a687dad7f83b0b1d82bc057f65309fa03a89911/tensorflow_cpu-2.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
            sudo unzip tensorflow_cpu-2.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          else
            curl -O https://files.pythonhosted.org/packages/06/d5/05cd02db299821fd68ef5f8857506c21aeeddd024daf519d8643f0260952/tensorflow_cpu_aws-2.15.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
            sudo unzip tensorflow_cpu_aws-2.15.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
            sudo mv /tmp/tensorflow_cpu_aws.libs/libomp-54bf90fd.so.5 /usr/lib/
          fi
          sudo mv /tmp/tensorflow/libtensorflow_cc.so.2 /usr/lib/
          sudo mv /tmp/tensorflow/libtensorflow_framework.so.2 /usr/lib/
          sudo ln -s /usr/lib/libtensorflow_cc.so.2 /usr/lib/libtensorflow_cc.so
          sudo ln -s /usr/lib/libtensorflow_framework.so.2 /usr/lib/libtensorflow_framework.so
          sudo ldconfig
          sudo printf "prefix=/usr\nexec_prefix=\${prefix}\nlibdir=\${exec_prefix}/lib\nincludedir=\${prefix}/include/tensorflow\n\nName: TensorFlow\nVersion: 2.15.1\nDescription: Library for computation using data flow graphs for scalable machine learning\nRequires:\nLibs: -L\${libdir} -ltensorflow_cc -ltensorflow_framework\nCflags: -I\${includedir}" > /usr/lib/pkgconfig/tensorflow.pc
          sudo rm -rf /tmp/*

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Cheminee
        run: cargo install --path cheminee/

      - name: Write Out Spec
        run: cheminee rest-api-server spec -o openapi.json

      - uses: bluwy/substitute-string-action@v2.0.1
        id: ref_name
        with:
          _input-text: ${{  github.ref_name }}
          v: ""

      - name: Generate Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: ruby
          config-file: cheminee-ruby/openapi-generator-config.json
          openapi-file: openapi.json
          command-args: "--additional-properties='gemVersion=${{  steps.ref_name.outputs.result }} --library=faraday' --output=cheminee-ruby"

      - run: echo "Gemfile.lock" >> cheminee-ruby/.gitignore

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated Commit"
          repository: cheminee-ruby
          tagging_message: ${{  steps.ref_name.outputs.result }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: cheminee-ruby
          ruby-version: 3.2.2

      - name: Release
        working-directory: cheminee-ruby
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials

          bundle install
          rake build
          git status
          rake release:rubygem_push

#      - name: Release Gem
#        if: contains(github.ref, 'refs/tags/v')
#        uses: cadwallion/publish-rubygems-action@master
#        env:
#          WORKDIR: cheminee-ruby
#          GITHUB_TOKEN: ${{ secrets.SCIENTIST_SERVICE_CHEMINEE_RUBY_GITHUB_TOKEN }}
#          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
#          RELEASE_COMMAND: rake release
