name: Publish custom cross images

on:
  workflow_dispatch:
  push: {}
#    branches:
#      - main
#    paths:
#      - "build/cross-images/*"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
#        platform: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
        platform: [x86_64-unknown-linux-gnu]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:build-${{ matrix.platform }}
          context: build/cross-images
          file: build/cross-images/${{ matrix.platform }}.dockerfile
